title: Berdax Tlepov
email: berdakh2024@gmail.com
description: >-
  Programmist balanıń pikirleri
baseurl: ""
url: "https://berdax.github.io"
remote_theme: chesterhow/tale
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
permalink: /:year-:month-:day/:title