title: Berdax Tlepov
email: berdakh2024@gmail.com
description: "Programmist balanıń pikirleri"
url: "https://berdax.github.io"
baseurl: "" # Add this if deploying to a subdirectory; leave empty for root
remote_theme: chesterhow/tale
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year/:month/:day/:title
paginate:       10

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: /:year-:month-:day/:title